# Each gitlab batch runner is tied to a specific environment variable for the scheduler paramaters
# jlsebatch[1-2] - are generic batch executors and can be used for submitting to any JLSE system. They use JLSE_SCHEDULER_PARAMETERS

# This is a global before script it will be ran as the first part of each job
before_script:
  - echo "before script"

stages:
  - shell
  - v100
  - mi100
  - pvc

# Shell executor will be executed like you are logged in directly to a JLSE login node
shell_executor:
  stage: shell
  needs: []
  tags:
    - shell
  script:
    - id
    - hostname
    - echo "Running on $(hostname) with setuid shell runner"

# Arcticus using Generic batch executor  
pvc:
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-n 1  -t 120 -q florentia"
  stage: pvc
  needs: []
  tags:
    - batch
  script:
    - echo "SYCL test start"
    - id
    - hostname
    - echo "Running on $(hostname) with setuid batch runner on PVC with generic batch"
    - module load oneapi
    - module load cmake
    - export ZE_AFFINITY_MASK=0.0
    - echo "Compiling the performance testing variant"
    - make clean
    - make sycl
    - echo "Running the performance test"
    - time bin/librett_test
    - echo "Compiling the full code"
    - make clean
    - make sycl groupsize=32 tests=all
    - echo "Running the full test"
    - time bin/librett_test
    - echo "Compiling by using CMake"
    - make clean
    - cmake -H. -Bbuild -DENABLE_SYCL=ON -DCMAKE_CXX_COMPILER=icpx
    - cd build; make
    - echo "Running CMake tests"
    - ctest
    - echo "SYCL test end"

# V100 nodes using Generic batch executor  
v100:
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-n 1  -t 30 -q gpu_v100_smx2_debug"
  stage: v100
  needs: []
  tags:
    - batch
  script:
    - echo "CUDA test start"
    - id
    - hostname
    - echo "Running on $(hostname) with setuid batch runner on v100 with generic batch"
    - module load oneapi
    - module load cmake
    - module load cuda/11.2.0
    - export MPIR_CVAR_ENABLE_GPU=0
    - echo "Compiling the performance testing variant"
    - make clean
    - make cuda
    - echo "Running the performance test"
    - time bin/librett_test
    - echo "Compiling the full code"
    - make clean
    - make cuda tests=all
    - echo "Running the full test"
    - time bin/librett_test
    - echo "Compiling by using CMake"
    - make clean
    - cmake -H. -Bbuild -DENABLE_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=70
    - cd build; make
    - echo "Running CMake tests"
    - ctest
    - echo "CUDA test end"

# MI100 nodes using Generic batch executor  
#  needs: ["v100"]
mi100:
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-n 1  -t 30 -q gpu_amd_mi100"
  stage: mi100
  needs: []
  tags:
    - batch
  script:
    - echo "HIP test start"
    - id
    - hostname
    - echo "Running on $(hostname) with setuid batch runner on mi100 with generic batch"
    - export MPIR_CVAR_ENABLE_GPU=0
    - echo "Compiling the performance testing variant"
    - module use /soft/modulefiles
    - module load rocm/5.5.0 cmake
    - make clean
    - make hip
    - echo "Running the performance test"
    - time bin/librett_test
    - echo "Compiling the full code"
    - make clean
    - make hip tests=all
    - echo "Running the full test"
    - time bin/librett_test
    - echo "Compiling by using CMake"
    - make clean
    - cmake -H. -Bbuild -DENABLE_HIP=ON -DCMAKE_CXX_COMPILER=hipcc -DCMAKE_HIP_ARCHITECTURES=gfx908
    - cd build; make
    - echo "Running CMake tests"
    - ctest
    - echo "HIP test end"

# afer script to be executed after each job
after_script:
  - echo "after script"
