# Each gitlab batch runner is tied to a specific environment variable for the scheduler paramaters
# jlsebatch[1-2] - are generic batch executors and can be used for submitting to any JLSE system. They use JLSE_SCHEDULER_PARAMETERS

# This is a global before script it will be ran as the first part of each job
before_script:
  - echo "before script"

stages:
  - shell
  - arcticus
  - v100

# Shell executor will be executed like you are logged in directly to a JLSE login node
shell_executor:
  stage: shell
  needs: []
  tags:
    - shell
  script:
    - id
    - hostname
    - echo "Running on $(hostname) with setuid shell runner"

# Arcticus using Generic batch executor  
arcticus_batch_executor:
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-n 1  -t 20 -q arcticus"
  stage: arcticus
  needs: []
  tags:
    - batch
  script:
    - echo "SYCL test start"
    - id
    - hostname
    - echo "Running on $(hostname) with setuid batch runner on arcticus with generic batch"
    - module load oneapi
<<<<<<< HEAD
    - make clean
    - make sycl option=-DPERFTEST
    - time bin/test
    - make clean
    - make sycl
    - time bin/test
    - echo "Job 2 end"
=======
    - module load cmake
    - echo "Compilation of performance variant"
    - make clean
    - make sycl option=-DPERFTEST
    - echo "Run performance test"
    - time bin/librett_test
    - echo "Compilation of full code"
    - make clean
    - make sycl
    - echo "Run full test"
    - time bin/librett_test
    - echo "Compilation by using CMake"
    - cmake -H. -Bbuild -DENABLE_SYCL=ON -DCMAKE_CXX_COMPILER=icpx
    - cd build; make; make librett_test; make librett_bench; make test
    - echo "Run quick test"
    - time src/test
    - echo "Run bench test"
    - time src/librett_bench -bench 3
    - echo "SYCL test end"
>>>>>>> 1c1aa9e (Update CI test)

# V100 nodes using Generic batch executor  
test_v100_batch_generic:
  variables:
    JLSE_SCHEDULER_PARAMETERS: "-n 1  -t 10 -q gpu_v100_smx2_debug"
  stage: v100
  needs: []
  tags:
    - batch
  script:
    - echo "Job 2 start"
    - id
    - hostname
    - echo "Running on $(hostname) with setuid batch runner on v100 with generic batch"
    - echo "Job 2 end"

# afer script to be executed after each job
after_script:
  - echo "after script"
